import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/dose_log.dart';
import '../models/medicine.dart';
import '../models/user_profile.dart';
import '../utils/time_formatter.dart';

class PdfExportService {
  // Bundled Noto Sans Bengali so Bangla patient/note text does not crash the
  // PDF's built-in Latin fonts. Fonts are loaded once and cached.
  static const String _fontAssetRegular =
      'assets/fonts/NotoSansBengali-Regular.ttf';
  static const String _fontAssetBold = 'assets/fonts/NotoSansBengali-Bold.ttf';

  static pw.Font? _baseFont;
  static pw.Font? _boldFont;

  static Future<void> _loadFonts() async {
    if (_baseFont != null) return;
    try {
      _baseFont = pw.Font.ttf(await rootBundle.load(_fontAssetRegular));
      _boldFont = pw.Font.ttf(await rootBundle.load(_fontAssetBold));
    } catch (_) {
      // Fall back to the PDF package's built-in fonts (Latin-only).
      _baseFont = null;
      _boldFont = null;
    }
  }

  static String generateDoctorSummaryReport({
    required UserProfile profile,
    required List<Medicine> medicines,
    required List<DoseLog> recentLogs,
  }) {
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy, hh:mm a').format(now);

    final sb = StringBuffer();
    sb.writeln('====================================================');
    sb.writeln('          MEDITRACK CLINICAL MEDICATION SUMMARY      ');
    sb.writeln('====================================================');
    sb.writeln('Generated: $dateStr');
    sb.writeln('');
    sb.writeln('--- PATIENT DETAILS ---');
    sb.writeln('Name: ${profile.displayName}');
    sb.writeln('Email: ${profile.email}');
    sb.writeln('Blood Group: ${profile.bloodGroup ?? "Not specified"}');
    sb.writeln('Known Allergies: ${profile.allergies ?? "None recorded"}');
    if (profile.doctorName != null) {
      sb.writeln('Attending Doctor: ${profile.doctorName} (${profile.doctorPhone ?? "No phone"})');
    }
    if (profile.emergencyContactName != null) {
      sb.writeln('Emergency Contact: ${profile.emergencyContactName} (${profile.emergencyContactPhone ?? "No phone"})');
    }
    sb.writeln('');

    sb.writeln('--- ACTIVE MEDICATIONS (${medicines.length}) ---');
    if (medicines.isEmpty) {
      sb.writeln('No active medications currently registered in MediTrack.');
    } else {
      for (int i = 0; i < medicines.length; i++) {
        final m = medicines[i];
        sb.writeln('${i + 1}. ${m.name} ${m.strength != null ? "(${m.strength})" : ""}');
        if (m.genericName != null) sb.writeln('   Generic: ${m.genericName}');
        sb.writeln('   Form: ${m.dosageForm ?? "tablet"} | Dose Amount: ${m.schedule.doseAmount}');
        sb.writeln('   Times: ${m.schedule.doseTimes.map(TimeFormatter.format24To12Hour).join(", ")}');
        sb.writeln('   Days: ${TimeFormatter.formatDaysOfWeek(m.schedule.daysOfWeek)}');
        sb.writeln('   Current Stock: ${m.quantityCurrent} / ${m.quantityTotal} units');
        if (m.expiryDate != null) {
          sb.writeln('   Expiry Date: ${DateFormat("dd/MM/yyyy").format(m.expiryDate!)}');
        }
        sb.writeln('');
      }
    }

    sb.writeln('--- RECENT ADHERENCE SUMMARY ---');
    if (recentLogs.isEmpty) {
      sb.writeln('No dose events recorded in the last 7 days.');
    } else {
      final takenCount =
          recentLogs.where((l) => l.status == DoseStatus.taken).length;
      final skippedCount =
          recentLogs.where((l) => l.status == DoseStatus.skipped).length;
      final total = recentLogs.length;
      final adherencePercent = ((takenCount / total) * 100).toStringAsFixed(1);

      sb.writeln('Recorded Doses: $total');
      sb.writeln('Taken: $takenCount | Skipped: $skippedCount');
      sb.writeln('Adherence Rate: $adherencePercent%');
    }
    sb.writeln('');
    sb.writeln('====================================================');
    sb.writeln('Note: This report is generated by MediTrack for personal medical review.');
    sb.writeln('====================================================');

    return sb.toString();
  }

  /// Builds the doctor summary as a shareable PDF document (bytes).
  static Future<Uint8List> generateDoctorSummaryPdf({
    required UserProfile profile,
    required List<Medicine> medicines,
    required List<DoseLog> recentLogs,
  }) async {
    await _loadFonts();

    final doc = pw.Document(
      theme: _baseFont != null
          ? pw.ThemeData.withFont(
              base: _baseFont!,
              bold: _boldFont ?? _baseFont!,
            )
          : null,
    );

    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy, hh:mm a').format(now);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(36, 40, 36, 36),
        build: (context) => [
          pw.Center(
            child: pw.Text(
              'MediTrack — Clinical Medication Summary',
              style: pw.TextStyle(
                fontSize: 15,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.teal900,
              ),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Center(
            child: pw.Text(
              'Generated: $dateStr',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
            ),
          ),
          pw.SizedBox(height: 16),
          _sectionTitle('Patient Details'),
          _infoLine('Name', profile.displayName),
          _infoLine('Email', profile.email),
          _infoLine('Blood Group', profile.bloodGroup ?? 'Not specified'),
          _infoLine('Known Allergies', profile.allergies ?? 'None recorded'),
          if (profile.doctorName != null)
            _infoLine(
              'Attending Doctor',
              '${profile.doctorName} (${profile.doctorPhone ?? "No phone"})',
            ),
          if (profile.emergencyContactName != null)
            _infoLine(
              'Emergency Contact',
              '${profile.emergencyContactName} (${profile.emergencyContactPhone ?? "No phone"})',
            ),
          pw.SizedBox(height: 16),
          _sectionTitle('Active Medications (${medicines.length})'),
          if (medicines.isEmpty)
            _bodyText('No active medications currently registered in MediTrack.')
          else
            ...medicines.asMap().entries.map(
                  (entry) => _medicineBlock(
                    index: entry.key + 1,
                    medicine: entry.value,
                  ),
                ),
          pw.SizedBox(height: 16),
          _sectionTitle('Recent Adherence Summary'),
          ..._adherenceLines(recentLogs),
          pw.SizedBox(height: 24),
          pw.Divider(color: PdfColors.grey400),
          pw.SizedBox(height: 4),
          pw.Text(
            'This report is generated by MediTrack for personal medical review.',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _sectionTitle(String title) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.teal800,
              letterSpacing: 0.8,
            ),
          ),
          pw.SizedBox(height: 3),
          pw.Container(
            height: 1,
            color: PdfColors.teal100,
          ),
        ],
      ),
    );
  }

  static pw.Widget _infoLine(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 110,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 9.5,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value,
              style: const pw.TextStyle(fontSize: 9.5, color: PdfColors.grey900),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _bodyText(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 3),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 9.5, color: PdfColors.grey900),
      ),
    );
  }

  static pw.Widget _medicineBlock({
    required int index,
    required Medicine medicine,
  }) {
    final m = medicine;
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey50,
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            '$index. ${m.name}${m.strength != null ? " (${m.strength})" : ""}',
            style: pw.TextStyle(
              fontSize: 10.5,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey900,
            ),
          ),
          if (m.genericName != null) _bodyText('Generic: ${m.genericName}'),
          _bodyText(
            'Form: ${m.dosageForm ?? "tablet"}  |  Dose Amount: ${m.schedule.doseAmount}',
          ),
          _bodyText(
            'Times: ${m.schedule.doseTimes.map(TimeFormatter.format24To12Hour).join(", ")}',
          ),
          _bodyText(
            'Days: ${TimeFormatter.formatDaysOfWeek(m.schedule.daysOfWeek)}',
          ),
          _bodyText(
            'Current Stock: ${m.quantityCurrent} / ${m.quantityTotal} units',
          ),
          if (m.expiryDate != null)
            _bodyText(
              'Expiry Date: ${DateFormat("dd/MM/yyyy").format(m.expiryDate!)}',
            ),
        ],
      ),
    );
  }

  static List<pw.Widget> _adherenceLines(List<DoseLog> recentLogs) {
    if (recentLogs.isEmpty) {
      return [_bodyText('No dose events recorded in the last 7 days.')];
    }

    final takenCount =
        recentLogs.where((l) => l.status == DoseStatus.taken).length;
    final skippedCount =
        recentLogs.where((l) => l.status == DoseStatus.skipped).length;
    final total = recentLogs.length;
    final adherencePercent = ((takenCount / total) * 100).toStringAsFixed(1);

    return [
      _bodyText('Recorded Doses: $total'),
      _bodyText('Taken: $takenCount | Skipped: $skippedCount'),
      _bodyText('Adherence Rate: $adherencePercent%'),
    ];
  }
}
