import 'package:intl/intl.dart';
import '../models/dose_log.dart';
import '../models/medicine.dart';
import '../models/user_profile.dart';
import '../utils/time_formatter.dart';

class PdfExportService {
  static String generateDoctorSummaryReport({
    required UserProfile profile,
    required List<Medicine> medicines,
    required List<DoseLog> recentLogs,
  }) {
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMMM yyyy, hh:mm a').format(now);

    final sb = StringBuffer();
    sb.writeln('====================================================');
    sb.writeln('          MEDITRACK CLINICAL MEDICATION SUMMARY      ');
    sb.writeln('====================================================');
    sb.writeln('Generated: $dateStr');
    sb.writeln('');
    sb.writeln('--- PATIENT DETAILS ---');
    sb.writeln('Name: ${profile.displayName}');
    sb.writeln('Email: ${profile.email}');
    sb.writeln('Blood Group: ${profile.bloodGroup ?? "Not specified"}');
    sb.writeln('Known Allergies: ${profile.allergies ?? "None recorded"}');
    if (profile.doctorName != null) {
      sb.writeln('Attending Doctor: ${profile.doctorName} (${profile.doctorPhone ?? "No phone"})');
    }
    if (profile.emergencyContactName != null) {
      sb.writeln('Emergency Contact: ${profile.emergencyContactName} (${profile.emergencyContactPhone ?? "No phone"})');
    }
    sb.writeln('');

    sb.writeln('--- ACTIVE MEDICATIONS (${medicines.length}) ---');
    if (medicines.isEmpty) {
      sb.writeln('No active medications currently registered in MediTrack.');
    } else {
      for (int i = 0; i < medicines.length; i++) {
        final m = medicines[i];
        sb.writeln('${i + 1}. ${m.name} ${m.strength != null ? "(${m.strength})" : ""}');
        if (m.genericName != null) sb.writeln('   Generic: ${m.genericName}');
        sb.writeln('   Form: ${m.dosageForm ?? "tablet"} | Dose Amount: ${m.schedule.doseAmount}');
        sb.writeln('   Times: ${m.schedule.doseTimes.map(TimeFormatter.format24To12Hour).join(", ")}');
        sb.writeln('   Days: ${TimeFormatter.formatDaysOfWeek(m.schedule.daysOfWeek)}');
        sb.writeln('   Current Stock: ${m.quantityCurrent} / ${m.quantityTotal} units');
        if (m.expiryDate != null) {
          sb.writeln('   Expiry Date: ${DateFormat("dd/MM/yyyy").format(m.expiryDate!)}');
        }
        sb.writeln('');
      }
    }

    sb.writeln('--- RECENT ADHERENCE SUMMARY ---');
    if (recentLogs.isEmpty) {
      sb.writeln('No dose events recorded in the last 7 days.');
    } else {
      final takenCount =
          recentLogs.where((l) => l.status == DoseStatus.taken).length;
      final skippedCount =
          recentLogs.where((l) => l.status == DoseStatus.skipped).length;
      final total = recentLogs.length;
      final adherencePercent = ((takenCount / total) * 100).toStringAsFixed(1);

      sb.writeln('Recorded Doses: $total');
      sb.writeln('Taken: $takenCount | Skipped: $skippedCount');
      sb.writeln('Adherence Rate: $adherencePercent%');
    }
    sb.writeln('');
    sb.writeln('====================================================');
    sb.writeln('Note: This report is generated by MediTrack for personal medical review.');
    sb.writeln('====================================================');

    return sb.toString();
  }
}
