// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92YFvysAvUOFP_Oez8V7oJGXy2VCQPt4',
    appId: '1:363299282373:web:ccc0264ee9011f379effac',
    messagingSenderId: '363299282373',
    projectId: 'meditrack-app-2026',
    authDomain: 'meditrack-app-2026.firebaseapp.com',
    storageBucket: 'meditrack-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jCOPrv6F0PiA1-0I50QNhz_0aw44J-Y',
    appId: '1:363299282373:android:c4d634dd172deb2f9effac',
    messagingSenderId: '363299282373',
    projectId: 'meditrack-app-2026',
    storageBucket: 'meditrack-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHuZ-G6xqO-oXP86wlsMBVIorzARFtHo',
    appId: '1:363299282373:ios:c4ed037a65603da49effac',
    messagingSenderId: '363299282373',
    projectId: 'meditrack-app-2026',
    storageBucket: 'meditrack-app-2026.firebasestorage.app',
    iosBundleId: 'com.meditrack.app.meditrack',
  );
}
